name: "Rust Lambda Builder"
description: "Build lambda binary of Cargo project"
author: Aaron Griffin
inputs:
  release:
    description: Build crate with --release
    required: true
    default: "true"
  git_credentials:
    description: "Git credentials - https://git-scm.com/docs/git-credential-store"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - uses: Swatinem/rust-cache@v1
    - uses: fusion-engineering/setup-git-credentials@v2.0.7
      if: inputs.git_credentials != ''
      with:
        credentials: ${{ inputs.git_credentials }}
    - run: |
        ARGS="--target x86_64-unknown-linux-musl"
        if [ "$RELEASE" == "true" ]; then
          ARGS="$ARGS --release"
        fi
        echo CARGO_ARGS=$ARGS >> $GITHUB_ENV
      shell: bash
      env:
        RELEASE: ${{ inputs.release }}
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: ${{ env.CARGO_ARGS }}
    - run: ${{ github.action_path }}/package.sh
      shell: bash
      env:
        RELEASE: ${{ inputs.release }}

branding:
  icon: box
  color: orange
